services:
  api:
    build: 
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: rag_api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  postgres:
    image: postgres:15
    container_name: rag_postgres
    restart: always
    environment:
      POSTGRES_USER: agno_user
      POSTGRES_PASSWORD: agno_password_123
      POSTGRES_DB: agno_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
